### ISSUE TITLE
correct 

### ISSUE THREAD

**Issue by lf22222** [shuwei666/Color-Constancy-PCC#1]
How can I use the trained network to predict illumination for my own image of any size and then correct it?

**Comment by shuwei666** [comment]
You can save your data into '.npy' format for fast loading and any image size will be ok.

**Comment by lf22222** [comment]
Ok, thank you for your answer.
I found that the test image size is (1,4,2) when testing, how is this achieved? Does it mean that if I convert the size of the image I want to correct to (1,4,2) and feed it into the trained model, then r and g will be predicted？
