### ISSUE TITLE
About the PolyU Pure Color dataset

### ISSUE THREAD

**Issue by YDDDDG** [shuwei666/Color-Constancy-PCC#2]
Hi, 
Thanks for your great job.
I'm willing to follow your work, could you please release the PolyU Pure Color dataset on BaiduNetDisk or update the url of the dataset？
(something wrong with the [link](https://connectpolyu-my.sharepoint.com/:f:/g/personal/21064184r_connect_polyu_hk/EjKJSnalMRpMn0nm4fJoIeEB34G9oxnu8MW7SYu2iSvC7g?e=qWFJi2) of the dataset on your personal website)

**Comment by shuwei666** [comment]
Thanks for your interest!

Here is the newest download link which includes the thumbnail and full-resolution dataset.

https://www.123865.com/s/eNurTd-oFWmH

Enjoy!
